name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: clone repo
        uses: actions/checkout@v2
      - name: Composer install
          uses: docker://composer:1.9.1
          with:
            args: install
        
      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist
