name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: clone repo
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

      - name: Test Composer
        run: composer --version

      - name: Install dependencies
        run: composer install  

      - name: Install SQLite
        run: sudo apt-get install sqlite3  

      - name: doctrine:database:create
        run: php bin/console doctrine:database:create

      - name: doctrine:migrations:diff
        run: php bin/console doctrine:migrations:diff

      - name: doctrine:migrations:migrate
        run: php bin/console doctrine:migrations:migrate      
